# Generated by Django 4.1 on 2024-09-18 19:59

from django.db import migrations, models
import taxi.validators


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=255, unique=True, validators=[taxi.validators.validate_license_number]),
        ),
    ]
